#dev repo
name: trigger tests
on: workflow_dispatch
jobs:
    trigger-test:
        runs-on: ubuntu-latest
        steps:
            - name: trigger tests in another repo
              uses: peter-evans/repository-dispatch@v2
              with:
                token: ${{ secrets.REPO_ACCESS_TOKEN }}
                repository: saileshwarbogam/workflows-test
                event-type: my-event
                client-payload: '{"github": ${{ toJson(github) }}}'
    