name: trigger tests

on:
  push:
    branches:
      - master
    paths:
      - "src/**"

jobs:
  trigger-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
        with:
          fetch-depth: 0  # Fetch all history, including tags

      - name: Get Latest Tag Name
        id: get_tag
        run: echo "::set-output name=tag_name::$(git describe --tags --abbrev=0)"

      - name: trigger tests in another repo
        uses: peter-evans/repository-dispatch@v2
        with:
          token: ${{ secrets.REPO_ACCESS_TOKEN }}
          repository: saileshwarbogam/workflows-test
          event-type: my-event
          client-payload: '{"github": "${{ steps.get_tag.outputs.tag_name }}" }'
